from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["legalconnect"]
collection = db["constitution_parts"]

# Data from search results
articles_data = {
    "1": "Article 1: Name and territory of the Union.\n(1) India, that is Bharat, shall be a Union of States.\n(2) The States and the territories thereof shall be as specified in the First Schedule.\n(3) The territory of India shall comprise—\n(a) the territories of the States;\n(b) the Union territories specified in the First Schedule; and\n(c) such other territories as may be acquired.",
    "2": "Article 2: Admission or establishment of new States.\nParliament may by law admit into the Union, or establish, new States on such terms and conditions as it thinks fit.",
    "3": "Article 3: Formation of new States and alteration of areas, boundaries or names of existing States.\nParliament may by law—\n(a) form a new State by separation of territory from any State or by uniting two or more States or parts of States or by uniting any territory to a part of any State;\n(b) increase the area of any State;\n(c) diminish the area of any State;\n(d) alter the boundaries of any State;\n(e) alter the name of any State.\n\nProvided that no Bill for the purpose shall be introduced in either House of Parliament except on the recommendation of the President and unless, where the proposal contained in the Bill affects the area, boundaries or name of any of the States, the Bill has been referred by the President to the Legislature of that State for expressing its views thereon...",
    "4": "Article 4: Laws made under articles 2 and 3 to provide for the amendment of the First and the Fourth Schedules and supplemental, incidental and consequential matters.",
    "5": "Article 5: Citizenship at the commencement of the Constitution.\nAt the commencement of this Constitution, every person who has his domicile in the territory of India and—\n(a) who was born in the territory of India; or\n(b) either of whose parents was born in the territory of India; or\n(c) who has been ordinarily resident in the territory of India for not less than five years immediately preceding such commencement,\nshall be a citizen of India.",
    "6": "Article 6: Rights of citizenship of certain persons who have migrated to India from Pakistan.",
    "7": "Article 7: Rights of citizenship of certain migrants to Pakistan.",
    "8": "Article 8: Rights of citizenship of certain persons of Indian origin residing outside India.",
    "9": "Article 9: Persons voluntarily acquiring citizenship of a foreign State not to be citizens.",
    "10": "Article 10: Continuance of the rights of citizenship.",
    "11": "Article 11: Parliament to regulate the right of citizenship by law.",
    "12": "Article 12: Definition.\nIn this Part, unless the context otherwise requires, 'the State' includes the Government and Parliament of India and the Government and the Legislature of each of the States and all local or other authorities within the territory of India or under the control of the Government of India.",
    "13": "Article 13: Laws inconsistent with or in derogation of the fundamental rights.\n(1) All laws in force in the territory of India immediately before the commencement of this Constitution, in so far as they are inconsistent with the provisions of this Part, shall, to the extent of such inconsistency, be void.\n(2) The State shall not make any law which takes away or abridges the rights conferred by this Part and any law made in contravention of this clause shall, to the extent of the contravention, be void.\n(3) In this article, unless the context otherwise requires, —\n(a) 'law' includes any Ordinance, order, bye-law, rule, regulation, notification, custom or usage having in the territory of India the force of law;\n(b) 'laws in force' includes laws passed or made by a Legislature or other competent authority in the territory of India before the commencement of this Constitution and not previously repealed...",
    "14": "Article 14: Equality before law.\nThe State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.",
    "15": "Article 15: Prohibition of discrimination on grounds of religion, race, caste, sex or place of birth.\n(1) The State shall not discriminate against any citizen on grounds only of religion, race, caste, sex, place of birth or any of them.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, place of birth or any of them, be subject to any disability, liability, restriction or condition with regard to—\n(a) access to shops, public restaurants, hotels and places of public entertainment; or\n(b) the use of wells, tanks, bathing ghats, roads and places of public resort maintained wholly or partly out of State funds or dedicated to the use of the general public.\n(3) Nothing in this article shall prevent the State from making any special provision for women and children.\n(4) Nothing in this article or in clause (2) of article 29 shall prevent the State from making any special provision for the advancement of any socially and educationally backward classes of citizens or for the Scheduled Castes and the Scheduled Tribes...",
    "16": "Article 16: Equality of opportunity in matters of public employment.\n(1) There shall be equality of opportunity for all citizens in matters relating to employment or appointment to any office under the State.\n(2) No citizen shall, on grounds only of religion, race, caste, sex, descent, place of birth, residence or any of them, be ineligible for, or discriminated against in respect of, any employment or office under the State...",
    "17": "Article 17: Abolition of Untouchability.\n'Untouchability' is abolished and its practice in any form is forbidden. The enforcement of any disability arising out of 'Untouchability' shall be an offence punishable in accordance with law.",
    "18": "Article 18: Abolition of titles.\n(1) No title, not being a military or academic distinction, shall be conferred by the State.\n(2) No citizen of India shall accept any title from any foreign State.\n(3) No person who is not a citizen of India shall, while he holds any office of profit or trust under the State, accept without the consent of the President any title from any foreign State...",
    "19": "Article 19: Protection of certain rights regarding freedom of speech, etc.\n(1) All citizens shall have the right—\n(a) to freedom of speech and expression;\n(b) to assemble peaceably and without arms;\n(c) to form associations or unions;\n(d) to move freely throughout the territory of India;\n(e) to reside and settle in any part of the territory of India; and\n(g) to practise any profession, or to carry on any occupation, trade or business...",
    "20": "Article 20: Protection in respect of conviction for offences.\n(1) No person shall be convicted of any offence except for violation of a law in force at the time of the commission of the Act charged as an offence, nor be subjected to a penalty greater than that which might have been inflicted under the law in force at the time of the commission of the offence.\n(2) No person shall be prosecuted and punished for the same offence more than once.\n(3) No person accused of any offence shall be compelled to be a witness against himself.",
    "21": "Article 21: Protection of life and personal liberty.\nNo person shall be deprived of his life or personal liberty except according to procedure established by law.",
    "22": "Article 22: Protection against arrest and detention in certain cases.\n(1) No person who is arrested shall be detained in custody without being informed, as soon as may be, of the grounds for such arrest nor shall he be denied the right to consult, and to be defended by, a legal practitioner of his choice.\n(2) Every person who is arrested and detained in custody shall be produced before the nearest magistrate within a period of twenty-four hours of such arrest excluding the time necessary for the journey from the place of arrest to the court of the magistrate...",
    "23": "Article 23: Prohibition of traffic in human beings and forced labour.\n(1) Traffic in human beings and begar and other similar forms of forced labour are prohibited and any contravention of this provision shall be an offence punishable in accordance with law.\n(2) Nothing in this article shall prevent the State from imposing compulsory service for public purposes, and in imposing such service the State shall not make any discrimination on grounds only of religion, race, caste or class or any of them.",
    "24": "Article 24: Prohibition of employment of children in factories, etc.\nNo child below the age of fourteen years shall be employed to work in any factory or mine or engaged in any other hazardous employment.",
    "25": "Article 25: Freedom of conscience and free profession, practice and propagation of religion.\n(1) Subject to public order, morality and health and to the other provisions of this Part, all persons are equally entitled to freedom of conscience and the right freely to profess, practise and propagate religion.\n(2) Nothing in this article shall affect the operation of any existing law or prevent the State from making any law—\n(a) regulating or restricting any economic, financial, political or other secular activity which may be associated with religious practice;\n(b) providing for social welfare and reform or the throwing open of Hindu religious institutions of a public character to all classes and sections of Hindus.",
    "26": "Article 26: Freedom to manage religious affairs.\nSubject to public order, morality and health, every religious denomination or any section thereof shall have the right—\n(a) to establish and maintain institutions for religious and charitable purposes;\n(b) to manage its own affairs in matters of religion;\n(c) to own and acquire movable and immovable property; and\n(d) to administer such property in accordance with law.",
    "27": "Article 27: Freedom as to payment of taxes for promotion of any particular religion.\nNo person shall be compelled to pay any taxes, the proceeds of which are specifically appropriated in payment of expenses for the promotion or maintenance of any particular religion or religious denomination.",
    "28": "Article 28: Freedom as to attendance at religious instruction or religious worship in certain educational institutions.\n(1) No religious instruction shall be provided in any educational institution wholly maintained out of State funds.\n(2) Nothing in clause (1) shall apply to an educational institution which is administered by the State but has been established under any endowment or trust which requires that religious instruction shall be imparted in such institution...",
    "29": "Article 29: Protection of interests of minorities.\n(1) Any section of the citizens residing in the territory of India or any part thereof having a distinct language, script or culture of its own shall have the right to conserve the same.\n(2) No citizen shall be denied admission into any educational institution maintained by the State or receiving aid out of State funds on grounds only of religion, race, caste, language or any of them.",
    "30": "Article 30: Right of minorities to establish and administer educational institutions.\n(1) All minorities, whether based on religion or language, shall have the right to establish and administer educational institutions of their choice.\n(1A) In making any law providing for the compulsory acquisition of any property belonging to an educational institution established and administered by a minority... the State shall ensure that the amount fixed... would not restrict or abrogate the right guaranteed under that clause.\n(2) The State shall not, in granting aid to educational institutions, discriminate against any educational institution on the ground that it is under the management of a minority, whether based on religion or language."
}

def update_articles():
    print("Updating Articles 1-30...")
    count = 0
    for article_id, content in articles_data.items():
        # Update content for each article
        result = collection.update_one(
            {"articles.id": article_id},
            {"$set": {"articles.$[elem].content": content}},
            array_filters=[{"elem.id": article_id}]
        )
        
        if result.modified_count > 0:
            print(f"✓ Updated Article {article_id}")
            count += 1
        elif result.matched_count > 0:
            print(f"- Article {article_id} already up to date")
            count += 1 # Count as success/checked
        else:
            print(f"✗ Article {article_id} NOT FOUND")
            
    print(f"\nFinished. Processed {count}/{len(articles_data)} articles.")

if __name__ == "__main__":
    update_articles()
